name: habito
description: Build habits in 21 days
version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  flutter_iconpicker: ^1.1.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.16
  email_validator: ^1.0.0
  scoped_model: ^1.0.1
  confetti: ^0.5.2
  store_redirect: ^1.0.2
  firebase_analytics: ^5.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: productsans
      fonts:
        - asset: assets/productsans.ttf
        - asset: assets/productsans_bold.ttf
          weight: 800
